language: android
dist : trusty
android:
  components:
    - build-tools-28.0.2
    - android-28
    - tools
    - platform-tools
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | ./sdkmanager "platforms;android-28"
  - yes | ./sdkmanager "build-tools;28.0.2"
  - yes | ./sdkmanager --licenses
  - chmod +x gradlew

script:
  - ./gradlew clean build